Internal Server Error: /posts/
Traceback (most recent call last):
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/programacionweb2/tp3env/TP3WebII/Blog/post/views.py", line 52, in post_list
    return render(request,'post/list.html',{'posts':posts,'tag':tag})
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_list_by_tag' with arguments '('nutrici√≥n',)' not found. 1 pattern(s) tried: ['posts/tag/(?P<tag_slug>[-a-zA-Z0-9_]+)/\\Z']
Internal Server Error: /posts/
Traceback (most recent call last):
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/programacionweb2/tp3env/TP3WebII/Blog/post/views.py", line 52, in post_list
    return render(request,'post/list.html',{'posts':posts,'tag':tag})
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_list_by_tag' with arguments '('nutrici√≥n',)' not found. 1 pattern(s) tried: ['posts/tag/(?P<tag_slug>[-a-zA-Z0-9_]+)/\\Z']
Internal Server Error: /posts/
Traceback (most recent call last):
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/programacionweb2/tp3env/TP3WebII/Blog/post/views.py", line 52, in post_list
    return render(request,'post/list.html',{'posts':posts,'tag':tag})
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_list_by_tag' with arguments '('nutrici√≥n',)' not found. 1 pattern(s) tried: ['posts/tag/(?P<tag_slug>[-a-zA-Z0-9_]+)/\\Z']
Internal Server Error: /posts/
Traceback (most recent call last):
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/programacionweb2/tp3env/TP3WebII/Blog/post/views.py", line 52, in post_list
    return render(request,'post/list.html',{'posts':posts,'tag':tag})
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_list_by_tag' with arguments '('tonificaci√≥n',)' not found. 1 pattern(s) tried: ['posts/tag/(?P<tag_slug>[-a-zA-Z0-9_]+)/\\Z']
Internal Server Error: /posts/
Traceback (most recent call last):
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/programacionweb2/tp3env/TP3WebII/Blog/post/views.py", line 52, in post_list
    return render(request,'post/list.html',{'posts':posts,'tag':tag})
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_list_by_tag' with arguments '('nutrici√≥n',)' not found. 1 pattern(s) tried: ['posts/tag/(?P<tag_slug>[-a-zA-Z0-9_]+)/\\Z']
Internal Server Error: /posts/post/create/
Traceback (most recent call last):
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/programacionweb2/tp3env/TP3WebII/Blog/post/views.py", line 145, in create_post
    return render(request, "post/create_post.html", {'form': form})
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/programacionweb2/tp3env/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: post/create_post.html
